name: Deploy API to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'api/**' # Only trigger when files in the api folder change

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Specify the Node.js version compatible with your CDK setup

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: Install dependencies
      run: npm install
      working-directory: ./api # Run npm install in the api folder

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Change to your AWS region

    - name: Deploy with AWS CDK
      run: cdk deploy --all --require-approval never
      working-directory: ./api # Run the CDK deploy command in the api folder
